### ISSUE TITLE
Error while using debugger

### ISSUE THREAD

**Issue by sandeep-paliwal** [apache/openwhisk-debugger#34]
Hi,
I have installed the debugger, but when I do basic command like list it throws following error - 

Welcome to the OpenWhisk Debugger

(wskdb) list
Available actions:
Error: entity does not exist while in this operation:  fetching actions
Unhandled rejection TypeError: Cannot read property 'filter' of undefined
    at print (/usr/local/lib/node_modules/openwhisk-debugger/lib/commands/list.js:45:6)
    at /usr/local/lib/node_modules/openwhisk-debugger/lib/repl-messages.js:49:6
    at tryCatcher (/usr/local/lib/node_modules/openwhisk-debugger/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/openwhisk-debugger/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/openwhisk-debugger/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/openwhisk-debugger/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/openwhisk-debugger/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/openwhisk-debugger/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/openwhisk-debugger/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by mrutkows** [comment]
Hi Sandeep,

According to the author of the debugger, Nick Mitchell, the debugger currently requires node 6 to 6.2, i believe. anything higher than 6.3 won't work.

Not sure what Node version you have tried.

Kind regards,
Matt

**Comment by starpit** [comment]
hi @sandeep-paliwal sorry for the delay in responding to you. we've been working on an update to this functionality. check it out here: https://openwhisk.ng.bluemix.net/api/v1/web/nickm_wskng_demos/public/index.html

the OpenWhisk Shell includes the debugger functionality. in the Shell, the debugger works with all versions of node 6 (whereas this github project only works with up to NodeJS 6.2). Also, with the Shell, you can download a platform release, avoiding the need for any local builds. let us know what you think!
